{% set name = "st-theme" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/st-theme-{{ version }}.tar.gz
  sha256: ca97aece1a48ded6e83fd742c27cb0851e1bce2100ab4b6c37c7b6e003b65b42

build:
  entry_points:
    - st-theme = streamlit_theme:print_version
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<=38]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - streamlit >=1.33

test:
  imports:
    - streamlit_theme
  commands:
    - pip check
    - st-theme --help
  requires:
    - pip

about:
  home: https://github.com/gabrieltempass/streamlit-theme
  summary: A component that returns the active theme of the Streamlit app.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
